### ISSUE TITLE
PhotoModularFX program icon hidden on black backgrounds

### ISSUE THREAD

**Issue by tannerhelland** [miorsoft/Site#1]
Hi reexre.  Sorry if this is a bad place to write you about a small PhotoModularFX suggestion.  I thought GitHub might be better than email, but if I'm wrong, I won't do this again!

I downloaded the latest PhotoModularFX today to check out all the neat features you've added, and I found that the PhotoModularFX taskbar icon is all black.  When extracting it to the desktop (or looking at its icon in the taskbar), if the user has a dark or black wallpaper like I do, it looks like PhotoModularFX has *no* icon.  It might be worthwhile to add a bright outline (or glow, maybe) to help the icon stand out against dark backgrounds, since dark Windows 10 themes are more common these days.

Another idea for the taskbar icon could be to reflect the currently loaded image, if any.  (GIMP is a good example of this.)

Just an idea.  Thanks for the great program.

**Comment by miorsoft** [comment]
hi, Sorry, I see your comment only now. Happy to hear from you.
Thank you very much for the suggestion. 
I tought about it. And I (wrongly) though that very few user could have Black/Dark wallpaper/Windows Themes
I do not remember what program I used to create the ICON.
Maybe Pixelformer. Do you have a suggestion of a program to create Icons ?
I used these layers
256x256 RGBA
128x128 RGBA
96x96 RGBA
48x48 RGBA
32x32 RGBA
24x24 RGB
16x16 256Colors
 
are them right? or too few/many ?

**Comment by tannerhelland** [comment]
No problem, sorry that I didn't post this somewhere that was easier to find!

I don't think this was a problem until Windows 10, due to the way it handles the taskbar.  Let me attach a screenshot like I should have in the first post...

![image](https://user-images.githubusercontent.com/1930029/41681539-244b5b1c-7492-11e8-8d46-347688e46c0d.png)

For icons, I'm afraid I am no expert.  :(  I have used GIMP in the past with good results.  Each layer represents a different icon, so you can create as many sizes+color depths as you want, and GIMP embeds them automatically when you export the icon file.

I think Microsoft has some guidelines for what color depths and sizes to use.  It is near the bottom of this page:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx

> **Application icons and Control Panel items:** The full set includes 16x16, 32x32, 48x48, and 256x256 (code scales between 32 and 256). 

> **Icon files require 8-bit and 4-bit palette versions as well,** to support the default setting in a remote desktop.

> Bit levels: ICO design for 32-bit (alpha included) + 8-bit + 4-bit (dithered down automatically—pixel poke only most critical). Only a 32-bit copy of the 256x256 pixel image should be included, and only the 256x256 pixel image should be compressed to keep the file size down.

As usual, they make the job awfully complicated!  Remote Desktop uses might be overkill, depending on your users.  It also sounds like you can skip 96x96 and 128x128 because the system can automatically create those from the 256x256 icon, as necessary.

Sorry if this is a lot of work!

(Also, what is the best way to submit feedback in the future?)

**Comment by miorsoft** [comment]
Thank you very much
At the moment I changed the Icon, (Same size**s** as before) I'll update soon.
For feedback it's ok here, or (reexre@gmail.com)

**Comment by tannerhelland** [comment]
Okay, sounds good.  Thanks!

(BTW the new icon is much easier to see against a dark background:

![image](https://user-images.githubusercontent.com/1930029/41852912-ac4535d2-7849-11e8-9593-463878da2e3e.png)

Good work!)
