### ISSUE TITLE
Mousewheel support for "picker" control

### ISSUE THREAD

**Issue by tannerhelland** [miorsoft/Site#2]
I'm not sure what the name is for this widget ([Apple calls it a "picker"](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/)):

![image](https://user-images.githubusercontent.com/1930029/41853169-6153f530-784a-11e8-9511-d8caa14d3b5d.png)

...but it would be very helpful to add mousewheel support, so you can quickly scroll through available options without clicking.  This is how closed dropdown boxes work on Windows 10 (you can mousewheel scroll the box without clicking it) and it makes exploring options much faster.

Thanks!

**Comment by miorsoft** [comment]
Thanks ! very nice suggestion !

**Comment by miorsoft** [comment]
In next update I will enable mousewheel in "TextInputValue" and "Slider" too.
PS: if you want full program send productKey to reexre@gmail.com (or here) and I'll send you ActivationKey

**Comment by tannerhelland** [comment]
Thank you for the kind offer!  I'm just glad the feedback is helpful instead of annoying.  :)

Here is the product key I see in the "About" window: 2742-CEEF-3F1B-191F-B3B6-3A07-35F8-E21C

I know it is hard to get feedback from the VB6 community, but hopefully other developers on GitHub will find your work.  I will try to send over ideas when I can.

(And feel free to close these Issues whenever you are finished with them!  I will try to not open too many at a time...)

**Comment by miorsoft** [comment]
2742-CEEF-3F1B-191F-B3B6-3A07-35F8-E21C
PK:
9B88ACB8417B891009797CA89F5269AF

**Comment by tannerhelland** [comment]
Thank you :bowtie:
