### ISSUE TITLE
Support alpha channels in 32-bit images

### ISSUE THREAD

**Issue by tannerhelland** [miorsoft/Site#5]
Would it be possible for PMFX to support alpha channels in 32-bit images?

Many modern images are 32-bit, and being able to manipulate the alpha channel alongside RGB would be helpful.  

If this is too cumbersome, even the ability to pass an initial alpha channel, unchanged, from starting state to final state (and having it saved properly to e.g. PNG format) would be very helpful, instead of losing the alpha channel completely, as the current version does.

Alternatively, if you don't want to support alpha channels, maybe there could be an option upon importing a 32-bit image to composite it against a white background.  (Or perhaps any color of the user's choosing?)  At present, 32-bpp images are always composited against black which is not always desirable.

**Comment by tannerhelland** [comment]
Okay, I am dumb and I JUST REALIZED there is already an INPUTA node.  I apologize for not noticing this before!

This makes me wonder if a different solution is needed, so that the same projects work properly on both 24 and 32-bit inputs... would it make sense for PMFX to automatically switch between INPUT and INPUTA nodes depending on the loaded image?

**Comment by tannerhelland** [comment]
My apologies @miorsoft, I have not thought through this very well.  I need to study PMFX in more detail before providing useful ideas on 24/32-bpp image handling.

I will open a new issue in the coming days after putting more thought into this issue.  Apologies for wasting your time!

**Comment by miorsoft** [comment]
Do not worry.
It's a lot of time I do not look at the email, so I read today.

The program was born without providing for the use of the alpha channel.
Each connection line practically represents a channel. (or a 2D surface).
Many modules (which do the same thing) have two versions, one for 1 channel only and another for 3 channels.
Such as: ADD, ADD3 - BLUR, BLUR3 - VALUE, VALUE3 - NORMALIZE - NORMALIZE3

At the moment I do not think to implement new modules to perform operations on 4 channels. I think, for example, not to create BLUR4.
It is feasible using BLUR3 on RGB channels, and BLUR on alpha channel.

Yes I know, it becomes a bit cumbersome. But at the moment I leave it as it is.

Current input / output modules:

  0: 3 INPUT The Loaded Picture

  0: 4 INPUT2 Secondary support Input picture

  0: 4 INPUTA The Loaded Picture with Alpha Channel

  3: 0 OUTPUT The Output (saved as Jpg Picture). If you need Alpha channel use PNGout Module

  4: 0 PNGOUT Save as PNG
